@KalkitechProductCatalogService_HostAddress = https://localhost:44347/api/ProductsCatalog

GET {{KalkitechProductCatalogService_HostAddress}}
Accept: application/json

###

GET {{KalkitechProductCatalogService_HostAddress}}/2
Accept: application/json

###



